runtime: python

env: flex

runtime_config:
  python_version: 3

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: main.app
resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10
automatic_scaling:
   min_num_instances: 1
   max_num_instances: 7  